Add files via upload
made-ml-in-prod-2021/lainer991 pull request #2
Opened 2021-05-09 20:22 UTC by lainer991

First commit of homework#1 ML in production. More info about project in readme.

2021-05-15 14:01 UTC, rchermanteev reviewed
Замечания:

- Можно расширить конфиг и тем самым сделать более вариативную и удобную настройку пайплайна
- Наверное, не стоит сохранять данные на гитхаб
- Программа в режиме запуска predict падает с ошибкой (легко поправляется, если посмотреть на код)
-  В задании просили 2 конфигурации для тренировки модели, увидел одну, но есть конфигурация для режима запуска predict
- Наверное, стоит перед коммитом использовать форматтер кода, например, black. Тем самым решив большую часть проблем с форматированием кода 
- Возможно, стоит подумать о более информативном логировании, может быть писать логи в файл. Так же стоит почитать про f-строки 

В целом работа выполнена хороша. Согласен с самооценкой. 
27 баллов.

2021-05-15 14:01 UTC, rchermanteev commented on ml_project/data/heart.csv
> +﻿age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
Не уверен, что класть данные на гитхаб - хорошая идея (даже в таком примере)

2021-05-15 14:01 UTC, rchermanteev commented on ml_project/entities/predict_pipeline_params.py
> +from dataclasses import dataclass
В entities попала папка __pycache__, такое пушить не стоит, надо добавить запись в .gitignore

2021-05-15 14:01 UTC, rchermanteev commented on ml_project/entities/train_pipeline_params.py
> +import yaml
Порядок импортов не по pep8 
1. импорты из стандартной библиотеки
2. импорты сторонних библиотек
3. импорты модулей текущего проекта

2021-05-15 14:01 UTC, rchermanteev commented on ml_project/module_functions/fit_predict_model.py
> +ESTIMATORS=300
Гиперпараметр модели лучше вынести в конфиг

2021-05-15 14:01 UTC, rchermanteev commented on ml_project/module_functions/fit_predict_model.py
> +    }
Используемые метрики тоже можно в конфиг вынести

2021-05-15 14:01 UTC, rchermanteev commented on ml_project/predict_pipeline.py
> +    logger.info(f"Start predict pipeline")
Лучше не использовать f-строки при логгировании. Может повлиять на скорость работы программы.

2021-05-15 14:01 UTC, rchermanteev commented on ml_project/predict_pipeline.py
> +    # data, y = extract_target(data,'target')
Из итогового кода комментарии лучше убрать.
Если эта строчка закомменчена, то программа падает с ошибкой:
ValueError: X has 32 features per sample; expecting 30
Если её раскомментировать, то всё ок

2021-05-15 14:01 UTC, rchermanteev commented on ml_project/tests/conftest.py
> +CONF_PATH = "ml_project/config/train_conf.yaml"
Можно вынести в конфиг

2021-05-15 14:01 UTC, rchermanteev commented on ml_project/tests/making_fake_data.py
> +RANDOM_PERCENT = 0.8
Тоже можно вынести в конфиг

2021-05-15 14:01 UTC, rchermanteev commented on ml_project/entities/train_pipeline_params.py
> +from typing import Optional
Неиспользуемый импорт

2021-05-15 14:01 UTC, rchermanteev commented on ml_project/module_functions/fit_predict_model.py
> +def train_model(
Отступы не по pep8

2021-05-15 14:01 UTC, rchermanteev commented on ml_project/entities/split_params.py
> +    random_state: int = field(default=13)
Нет переноса строки в конце файла - формат не по pep8

2021-05-17 08:01 UTC, kindofman requested changes

2021-05-17 08:01 UTC, kindofman commented on ml_project/requirements.txt
> +yaml~=0.2.5
Зачем здесь yaml~=0.2.5? У тебя он устанавливается через **pip install -r requirements.txt**?
Пайплайн на обучение работает без этого пакета.

2021-05-17 08:01 UTC, kindofman commented on ml_project/README.md
> +`python predict_pipeline.py config/predict_conf.yaml`
Кажется, что-то не так с размерностями. Поправь, пожалуйста.
<img width="1532" alt="lainer991" src="https://user-images.githubusercontent.com/43539680/118452079-8557bc00-b6fe-11eb-80d8-90551d8fe6f3.png">

2021-05-17 08:01 UTC, kindofman commented on ml_project/notebooks/EDA.ipynb
> +    "df = pd.read_csv('heart.csv')"
Поправь, чтобы все запускалось.

<img width="1253" alt="Снимок экрана 2021-05-17 в 10 51 10" src="https://user-images.githubusercontent.com/43539680/118452486-dff11800-b6fe-11eb-8e1f-2539e8db9912.png">

2021-05-18 11:32 UTC, lainer991 commented
@rchermanteev  @kindofman Спасибо за ревью! Я пока занят второй домашкой, после нее изменения по вашим комментам

2021-05-23 15:40 UTC, lainer991 commented
@rchermanteev @kindofman 

Поправил основные замечания.

2021-05-23 19:08 UTC, kindofman approved these changes
28 баллов

2021-05-24 10:16 UTC, merged