Homework2
made-ml-in-prod-2021/lainer991 pull request #3
Opened 2021-05-21 16:42 UTC by lainer991

Комичу второе дз, договаривались с Михаилом, что дает острочку в 2 дня с дедлайна.

2021-05-22 17:48 UTC, Mikhail-M requested changes
удалите все pyc

2021-05-25 16:57 UTC, biquaternion requested changes

2021-05-25 16:57 UTC, biquaternion commented on homework2/make_request.py
> +    with open(filepath, "w") as file:
Путь predictions (который в PREDICTION_FILEPATH) не существует в пустом репозитории, соответственно без наличия этой папки файл открываться и сохраняться не будет, если собирать from scratch.
Можно либо сделать mkdir прямо отсюда (парой строчек выше) либо сделать скрипт, который насоздаёт все нужные папки, установит PYTHONPATH и др.переменные, и его запускать перед использованием

2021-05-25 16:57 UTC, biquaternion commented on homework2/src/module_functions/make_data.py
> +# -*- coding: utf-8 -*-
Единственный файл, где встречается coding: utf-8
Я бы во все вставил и добавил шебанг #!/usr/bin/env python3

2021-05-25 16:57 UTC, biquaternion commented on homework2/tests/test_predict.py
> +def test_predict():
По смыслу больше похоже на test_entry

2021-05-25 17:03 UTC, biquaternion commented on homework2/README.md
> +|4.|Валидация не делалась|0|
pydantic BaseModel не считается за валидацию ?

2021-05-30 19:03 UTC, merged

2021-06-14 21:03 UTC, Mikhail-M commented
нет оценки

2021-07-15 13:46 UTC, Mikhail-M commented
10 баллов